[phases.setup]
nixPkgs = ["nodejs_18", "yarn", "python-38"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn start"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=4096"